spring:
  application:
    name: service-hi
server:
  port: 8763
eureka:
  client:
    eureka-server-port: 8763
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/